In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('/home/djden/Development/Science/FateOfFat/MDSS/Initial Data/db_nl_preprocessed.csv')
df

,возраст,пол,масса_тела,рост,от,об,оп,жм,мм,ож,...,селен_se,фтор_f,хром_cr,цинк_zn,профессия_работники_преимущественно_умственного_труда,профессия_работники_занятые_легким_физическим_трудом,спорт_легкий_спорт,спорт_не_занимаюсь,bmi,target
0,20.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.21,NaN,NaN,0.17,0,0,0,0,NaN,0
1,20.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.24,NaN,NaN,0.15,0,0,0,0,NaN,0
2,22.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.32,NaN,NaN,0.26,1,0,0,0,NaN,0
3,23.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,NaN,NaN,0.03,0,0,0,0,NaN,0
4,22.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.26,NaN,NaN,0.08,0,0,0,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2880,44.0,0,104.0,170.0,106.0,115.0,NaN,36.7,NaN,49.2,...,60.15,68.55,6.56,4.58,1,0,0,1,35.986159,0
2881,60.0,0,180.2,174.0,NaN,NaN,NaN,99.5,45.0,60.5,...,254.15,179.18,6.91,24.05,1,0,0,1,59.519091,1
2882,47.0,1,82.0,162.0,NaN,NaN,NaN,34.5,20.7,34.7,...,146.40,183.49,34.77,12.77,1,0,0,1,31.245237,1
2883,45.0,0,174.8,185.0,149.7,126.0,170.0,75.4,55.6,74.3,...,199.63,86.15,7.51,17.86,1,0,0,1,51.073776,1
2884,59.0,1,66.3,154.0,92.0,95.0,31.0,20.9,20.4,34.0,...,99.23,108.69,12.95,11.08,1,0,1,0,27.955810,1

In [7]:
data_filled = df.fillna(df.mean())

In [8]:
data_filled

,возраст,пол,масса_тела,рост,от,об,оп,жм,мм,ож,...,селен_se,фтор_f,хром_cr,цинк_zn,профессия_работники_преимущественно_умственного_труда,профессия_работники_занятые_легким_физическим_трудом,спорт_легкий_спорт,спорт_не_занимаюсь,bmi,target
0,20.0,1,88.047086,167.84654,99.989344,109.849791,45.562857,38.410873,32.363534,42.018453,...,0.21,110.906262,14.00073,0.17,0,0,0,0,31.194825,0
1,20.0,0,88.047086,167.84654,99.989344,109.849791,45.562857,38.410873,32.363534,42.018453,...,0.24,110.906262,14.00073,0.15,0,0,0,0,31.194825,0
2,22.0,1,88.047086,167.84654,99.989344,109.849791,45.562857,38.410873,32.363534,42.018453,...,0.32,110.906262,14.00073,0.26,1,0,0,0,31.194825,0
3,23.0,0,88.047086,167.84654,99.989344,109.849791,45.562857,38.410873,32.363534,42.018453,...,0.17,110.906262,14.00073,0.03,0,0,0,0,31.194825,0
4,22.0,0,88.047086,167.84654,99.989344,109.849791,45.562857,38.410873,32.363534,42.018453,...,0.26,110.906262,14.00073,0.08,0,0,0,0,31.194825,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2880,44.0,0,104.000000,170.00000,106.000000,115.000000,45.562857,36.700000,32.363534,49.200000,...,60.15,68.550000,6.56000,4.58,1,0,0,1,35.986159,0
2881,60.0,0,180.200000,174.00000,99.989344,109.849791,45.562857,99.500000,45.000000,60.500000,...,254.15,179.180000,6.91000,24.05,1,0,0,1,59.519091,1
2882,47.0,1,82.000000,162.00000,99.989344,109.849791,45.562857,34.500000,20.700000,34.700000,...,146.40,183.490000,34.77000,12.77,1,0,0,1,31.245237,1
2883,45.0,0,174.800000,185.00000,149.700000,126.000000,170.000000,75.400000,55.600000,74.300000,...,199.63,86.150000,7.51000,17.86,1,0,0,1,51.073776,1
2884,59.0,1,66.300000,154.00000,92.000000,95.000000,31.000000,20.900000,20.400000,34.000000,...,99.23,108.690000,12.95000,11.08,1,0,1,0,27.955810,1

In [9]:
missing_values_remaining = data_filled.isnull().sum().sum()
missing_values_remaining

0

In [10]:
data_filled.to_csv('/home/djden/Development/Science/FateOfFat/MDSS/Processed Data/db_nl_mean.csv')